In [2]:
from src.FeedForward import feed_forward

import pandas as pd
import numpy as np

data = pd.read_csv('./Data/clean_weather.csv', index_col=[0])

data = data.ffill()
data = data['tmax'].head(10)
data

feed_forward(num_neurons=3, data = data)

(3, 1)


[array([[38.44222947]]),
 array([[35.46793899]]),
 array([[35.46793899]]),
 array([[36.03995463]]),
 array([[35.46793899]]),
 array([[34.32390772]]),
 array([[35.46793899]]),
 array([[37.75600153]]),
 array([[36.61197026]]),
 array([[38.32801717]])]