In [16]:
from FeedForward import feed_forward

import pandas as pd
import numpy as np

data = pd.read_csv('./clean_weather.csv', index_col=[0])

data = data.ffill()
data = data['tmax'].head(10)
data

feed_forward(num_neurons=3, data = data)

(3, 1)


[array([[60.23852802]]),
 array([[53.81220164]]),
 array([[53.81220164]]),
 array([[54.76788695]]),
 array([[53.81220164]]),
 array([[51.90083101]]),
 array([[53.81220164]]),
 array([[57.63494289]]),
 array([[55.72357227]]),
 array([[58.59062821]])]